name: age
slug: age
description: A simple, modern and secure encryption tool
scope: user
target:
  os: [linux, darwin]
  arch: [amd64, arm64]

artifact:
  name: age
  version:
    type: githubRelease
    repo: FiloSottile/age
  urlTemplate: >
    https://github.com/FiloSottile/age/releases/download/v{{ .Version }}/age-v{{ .Version }}-{{ .OS }}-{{ .Arch }}.tar.gz
  format: "tar.gz"
  innerPath: bin
  binName: "age"
  mode: "0755"
actions:
  - type: download
    args:
      url: "{{ .URL }}"
      dest: "{{ .CacheFile }}"
  - type: mkdir
    args:
      path: "{{ .InstallDir }}"
      mode: "0755"
  - type: extract
    args:
      src: "{{ .CacheFile }}"
      dest: "{{ .InstallDir }}"
  # chmod both binaries
  - type: chmod
    args:
      path: "{{ .InstallDir }}/age/age"
      mode: "0755"
  - type: chmod
    args:
      path: "{{ .InstallDir }}/age/age-keygen"
      mode: "0755"
  # create two symlinks in ~/.local/sth/bin
  - type: symlink
    args:
      src: "{{ .InstallDir }}/age/age"
      dest: "{{ .BinDir }}/age"
  - type: symlink
    args:
      src: "{{ .InstallDir }}/age/age-keygen"
      dest: "{{ .BinDir }}/age-keygen"